version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'diveanalytics-syncer-mongo'
    env_file:
        - .env
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./docker-init-mongo.js:/docker-entrypoint-initdb.d/docker-init-mongo.js:ro
      - mongodata:/data/db
    ports:
        # - '27017-27019:27017-27019'
        - '27017:27017'
volumes:
  mongodata:
